shiiii andubo

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -2,6 +2,14 @@
 
 echo '-----------------🚀Launching pre-commit hook-----------------'
 
+./gradlew ktlintFormat --daemon
+if [ $? -ne 0 ]; then
+  echo '❌ ktlintFormat failed. Please fix the issues before committing.'
+  exit 1
+fi
+
+git add -u
+
 ./gradlew build --daemon
 
 if [ $? -ne 0 ]; then
